version: '3.1'

services:
  db:
    image: postgres
    restart: never # or always
    env_file: .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: never # or always
    ports:
      - 8084:8080
